### ISSUE TITLE
input and target shapes do not match

### ISSUE THREAD

**Issue by Yaozl2018** [MIVRC/MSRN-PyTorch#10]
HI, thanks for your great work.
Now, i get some problem when i run your codes ( about training ). Could you please give me some advice to how to make it work?
THAT IS:
I want to train your network by DIV2K in X8 scale, but it give back me an error about shape do not match. 
My option are bellow:
```
root@docker18:/MSRN-PyTorch-master/MSRN/Train# CUDA_VISIBLE_DEVICES=13 python main.py --template MSRN --save MSRN_X8_DIV2K --scale 8 --reset --save_results --save_models --patch_size 384 --ext sep --epochs 100 --n_GPUs 1 --data_train DIV2K --data_test DIV2K --batch_size 1 --data_range 1-895/896-900 --n_threads 1
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]	Learning rate: 1.00e-4
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    t.train()
  File "/MSRN-PyTorch-master/MSRN/Train/trainer.py", line 55, in train
    loss = self.loss(sr, hr)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/yaozhaoliang/MSRN-PyTorch-master/MSRN/Train/loss/__init__.py", line 73, in forward
    loss = l['function'](sr, hr)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 87, in forward
    return F.l1_loss(input, target, reduction=self.reduction)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1702, in l1_loss
    input, target, reduction)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1674, in _pointwise_loss
    return lambd_optimized(input, target, reduction)
RuntimeError: input and target shapes do not match: input [1 x 3 x 384 x 384], target [1 x 3 x 380 x 384] at /pytorch/aten/src/THCUNN/generic/AbsCriterion.cu:12
```
Thank you again for your kindness help!

**Comment by CV-JunchengLi** [comment]
Hi~
Thank you for your attention.
I also used this code to train DIV2K in X8 scale.
The code is working fine and no errors have occurred.
I guess this may be because you have a wrong operation when building the X8 training dataset.
You can download the DIV2K x8 LR dataset from https://data.vision.ee.ethz.ch/cvl/DIV2K/

**Comment by huiliaohh** [comment]
Yes, this problem is caused by the size unmatch for LR images and HR images.
After i reproduced the LR images in a correct way (make sure the image width and height satisfy LR*8==HR), the codes work well.
Thank you very much.
