### ISSUE TITLE
issue about training x8 model

### ISSUE THREAD

**Issue by Jee-King** [MIVRC/MSRN-PyTorch#13]
Hi, I used the following command to train a x8 model.
` python3 main.py  --template MSRN --save MSRN_X8 --scale 8 --reset --save_results --patch_size 384 --ext sep`

 But I got an error as follow,
```
[Epoch 1]	Learning rate: 1.00e-4
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    t.train()
  File "/home/iccd/zjq/MSRN/MSRN/Train/trainer.py", line 45, in train
    for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/iccd/zjq/MSRN/MSRN/Train/dataloader.py", line 49, in _ms_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 187, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 187, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 164, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 384 and 380 in dimension 3 at /pytorch/aten/src/TH/generic/THTensorMath.cpp:3616
```
Could you give me some suggestions?

**Comment by MKFMIKU** [comment]
Hi, I think the reason for this problem is that you use images of different size as your training datasets.
As you know, the `Mini-Batch` in `Dataloader` assumes it loads images in the same size so that it can stack them into a single matrix.

**Comment by Jee-King** [comment]
@MKFMIKU Hi, I do not think that different size images lead to this problem.  Because function _get_patch()_ will make input_size is  48x48, and gt_size is 384x384

**Comment by MKFMIKU** [comment]
@Jee-King You can check the code here:https://github.com/MIVRC/MSRN-PyTorch/blob/d2c9aa480de238bdc7fee7fdc558bb48079f9e03/MSRN/Train/data/common.py#L16-L23

If `ty + tp` is bigger than the size of HR Image, `get_patch()` will return a image in size of `[ty: HR_Y]` instead of `[ty: ty + tp]`

**Comment by Jee-King** [comment]
@MKFMIKU  Thank you! I have changed _ix,iy_ so that _ty + tp_ can smaller than the size of HR Image.

**Comment by MKFMIKU** [comment]
😁OK
