### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Nibbles55** [MIVRC/MSRN-PyTorch#20]
您好，我想用自己的数据集来训练模型，但是出现了问题，可以麻烦您帮我看一下可以吗？
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]	Learning rate: 1.00e-4
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    t.train()
  File "/home/customer/Nibbles/SR/MSRN/RES2NET_MSRN/Train2/trainer.py", line 45, in train
    for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):
  File "/home/customer/.conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/customer/.conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/customer/Nibbles/SR/MSRN/RES2NET_MSRN/Train2/dataloader.py", line 47, in _ms_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/customer/Nibbles/SR/MSRN/RES2NET_MSRN/Train2/dataloader.py", line 47, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/customer/Nibbles/SR/MSRN/RES2NET_MSRN/Train2/data/srdata.py", line 151, in __getitem__
    lr, hr, rgb_range=self.args.rgb_range
  File "/home/customer/Nibbles/SR/MSRN/RES2NET_MSRN/Train2/data/common.py", line 50, in np2Tensor
    return [_np2Tensor(a) for a in args]
  File "/home/customer/Nibbles/SR/MSRN/RES2NET_MSRN/Train2/data/common.py", line 50, in <listcomp>
    return [_np2Tensor(a) for a in args]
  File "/home/customer/Nibbles/SR/MSRN/RES2NET_MSRN/Train2/data/common.py", line 45, in _np2Tensor
    tensor = torch.from_numpy(np_transpose).float()
RuntimeError: Trying to resize storage that is not resizable at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/TH/generic/THStorage.c:183

**Comment by MKFMIKU** [comment]
@Nibbles55 Hi, I think this problem is related to this issue https://github.com/pytorch/pytorch/issues/13404

**Comment by Nibbles55** [comment]
@MKFMIKU Hi, I want to ask if these two questions are the same error? Thank you very much.

RuntimeError: Trying to resize storage that is not resizable at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/TH/generic/**THStorage.c:183**
和
RuntimeError: Trying to resize storage that is not resizable at ../aten/src/TH/**THStorageFunctions.cpp:70**

**Comment by MKFMIKU** [comment]
I think you should try to update your pytorch version according to the issue.
If not, you can continue ask us. 😁

**Comment by Nibbles55** [comment]
@MKFMIKU    Thank you very much for your help. After updating the pytorch version, my problem was solved.
